### ISSUE TITLE
Tabula 5.1.0 Crashes Client when playing SMP or SSP and you place and power a sticky piston

### ISSUE THREAD

**Issue by kreezxil** [iChun/Tabula#70] opened 2015-06-07 19:20 UTC
https://gist.github.com/kreezxil/6b0d5017945589c31680#file-crash-2015-06-07_14-12-02-client-txt

https://gist.github.com/kreezxil/6b0d5017945589c31680#file-fml-client-latest-log

**Comment by iChun** [comment] 2015-06-07 19:24
It's not Tabula doing it.

**Comment by pau101** [comment] 2015-12-05 09:10
This crash is caused by the TileEntityRendererDispatcher class being initialized before the blockRenderDispatcher of Minecraft is assigned. This can happen if a TileEntitySpecialRenderer is bound during the FML pre-initialization phase, which is indeed being done by Tabula for TileEntityTabulaRasa.

**Comment by iChun** [comment] 2015-12-05 09:20
Hmm really? I'll have to check into this when I can

**Comment by pau101** [comment] 2015-12-05 10:41
Yeah, I've encountered this problem before and just encountered it with Tabula. Here are more specifics to why: When the TileEntityRendererDispatcher class is initialized a static instance is constructed which registers the vanilla tileentity renderers, one of those being TileEntityPistonRenderer. When a TileEntityPistonRenderer is constructed it will store Minecraft's blockRenderDispatcher into it's own field. So if the blockRenderDispatcher is null it will remain null and thus the crash occurs when it tries to render a moving block.

**Comment by iLexiconn** [comment] 2015-12-30 09:35
This got fixed in commit https://github.com/MinecraftForge/MinecraftForge/commit/db3e039b31f1a464ce201b2d8ca92bbd73009c4e

**Closed** 2021-06-10 10:37 UTC
